import { BotConfig } from './BotConfig.js';
import { BotLog } from './BotLog.js';
import { BotSession } from './BotSession.js';
import { FriendMessage } from './FriendMessage.js';
import { MatchRound } from './MatchRound.js';
import { PasswordReset } from './PasswordReset.js';
import { QuickCommand } from './QuickCommand.js';
import { ReplayUpload } from './ReplayUpload.js';
import { SessionMedia } from './SessionMedia.js';
import { SessionStat } from './SessionStat.js';
import { User } from './User.js';

User.hasOne(BotConfig, { foreignKey: 'userId', onDelete: 'CASCADE' });
BotConfig.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(PasswordReset, { foreignKey: 'userId', onDelete: 'CASCADE' });
PasswordReset.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(BotLog, { foreignKey: 'userId', onDelete: 'CASCADE' });
BotLog.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(QuickCommand, { foreignKey: 'userId', onDelete: 'CASCADE' });
QuickCommand.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(BotSession, { foreignKey: 'userId', onDelete: 'CASCADE' });
BotSession.belongsTo(User, { foreignKey: 'userId' });
BotSession.hasMany(ReplayUpload, { foreignKey: 'botSessionId', onDelete: 'SET NULL' });
ReplayUpload.belongsTo(BotSession, { foreignKey: 'botSessionId' });
BotSession.hasMany(SessionStat, { foreignKey: 'botSessionId', onDelete: 'CASCADE' });
SessionStat.belongsTo(BotSession, { foreignKey: 'botSessionId' });
BotSession.hasMany(SessionMedia, { foreignKey: 'botSessionId', onDelete: 'CASCADE' });
SessionMedia.belongsTo(BotSession, { foreignKey: 'botSessionId' });
User.hasMany(FriendMessage, { foreignKey: 'userId', onDelete: 'CASCADE' });
FriendMessage.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(MatchRound, { foreignKey: 'userId', onDelete: 'CASCADE' });
MatchRound.belongsTo(User, { foreignKey: 'userId' });
BotSession.hasMany(MatchRound, { foreignKey: 'botSessionId', onDelete: 'CASCADE' });
MatchRound.belongsTo(BotSession, { foreignKey: 'botSessionId' });
